name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '18'
          - '20'
          - '21'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm typecheck:scripts
      - run: pnpm generate-test
      - run: pnpm lint
      - run: pnpm typecheck:main
      - run: pnpm test
      - run: pnpm build
