name: CI
on:
  pull_request:
  push:
    branches:
    - $default-branch
  release:
    types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 10.x
        - 12.x
        - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn typecheck:scripts
    - run: yarn lint
    - run: yarn test
    - run: yarn build
