name: Update EastAsianWidth
on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile
    - run: yarn fetch
    - run: yarn generate
    - name: Dump EAW version
      id: dump_eaw_version
      run: echo "EAW_VERSION=$(yarn --silent dump-eaw-version)" >> $GITHUB_OUTPUT
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: feat/update-eaw
        commit-message: 'feat: update EastAsianWidth to ${{ steps.dump_eaw_version.outputs.EAW_VERSION }}'
        title: 'Update EastAsianWidth'
        body: |
          Update EastAsianWidth to ${{ steps.dump_eaw_version.outputs.EAW_VERSION }}
        delete-branch: true
